name: Build & Push Valheim
on:
  push:
    branches: [ main ]
    paths:
      - 'games/valheim/**'
      - '.github/workflows/build-valheim.yml'
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: games/valheim
          file: games/valheim/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/games:valheim-fixed
            ghcr.io/${{ env.OWNER_LC }}/games:valheim-${{ github.sha }}
