name: build elixir

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - dev/elixir/**

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  push:
    name: "elixir:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '1.12'
          - '1.13'
          - '1.14'
          - '1.15'
          - '1.16'
          - latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-qemu-action@v3
      
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/build-push-action@v6
        with:
          context: ./dev/elixir
          file: ./dev/elixir/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/goover/elixir:${{ matrix.tag }}
