name: build distro-archlinux
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - distros/archlinux/*
jobs:
  push:
    name: "archlinux:${{ matrix.oses }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        oses:
          - latest
          - base
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./distros/archlinux/${{ matrix.oses }}
          file: ./distros/archlinux/${{ matrix.oses }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/pteroforge/archlinux:${{ matrix.oses }}
