name: build games
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - games/**
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  push:
    name: "games:${{ matrix.game }}"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        game:
          - altv
          - conan
          - dayz
          - interstellarrift
          - mohaa
          - riskofrain2
          - samp
          - screeps
          - staxel
          - valheim
          - wurm
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # https://github.com/docker/build-push-action/issues/761#issuecomment-1575006515
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./games/${{ matrix.game }}
          file: ./games/${{ matrix.game }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
             ghcr.io/goover/games:${{ matrix.game }}
