name: Build Steam Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - steam/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [proton, proton-ubuntu]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./steam
          file: ./steam/${{ matrix.distro }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/goover/steam:${{ matrix.distro }}
          provenance: false
