name: build steamcmd

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # every Monday at 00:00
  push:
    branches:
      - main
    paths:
      - steamcmd/**

jobs:
  push:
    name: "steamcmd:${{ matrix.distro }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian
          - ubuntu

    steps:
      # Checkout repository
      - uses: actions/checkout@v5

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      # Log in to GitHub Container Registry
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with cache
      - name: Build and push SteamCMD image
        uses: docker/build-push-action@v6
        with:
          context: ./steamcmd
          file: ./steamcmd/${{ matrix.distro }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/goover/steamcmd:${{ matrix.distro }}
          # Cache only if image exists
          cache-from: type=registry,ref=ghcr.io/goover/steamcmd:${{ matrix.distro }} || echo "no cache"
          cache-to: type=registry,mode=max,ref=ghcr.io/goover/steamcmd:${{ matrix.distro }}-cache
